spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/food_delivery
    username: postgres
    password: 2001
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    open-in-view: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true
  messages:
    always-use-message-format: true
  security:
    user:
      name: admin
      password: admin123

bot:
  name: pdpfooddeliverybot
  token: 5227670217:AAHEpHh_2JAq3m7qB4bbJ2B9xudS5sAzNt4

springdoc:
  swagger-ui:
    path: /swagger-ui
    enabled: true
  api-docs:
    path: /api/docs

api:
  info:
    title: Review Service API
    description: API to fetch review details for product
    version: 1.0.0
    terms-of-service: http://boom.com/terms/
    contact:
      name: Review Service API Team
      email: apiteam@example.com
      url: http://boom.com/team
    license:
      name: Apache 2.0
      url: http://www.apache.org/licenses/LICENSE-2.0.html

service:
  prop:
    protocol: http
    ip: localhost
    port: 9090
    url: boom.uz